### ISSUE TITLE
https://beepb00p.xyz/ Down?

### ISSUE THREAD

**Issue by nomatica** [karlicoss/beepb00p#2]
I do not think this is on my end, but it seems your blog (might) be down.

**Comment by karlicoss** [comment]
Hmm, is it okay now? 
I guess it's possible that the server was upgrading so for a short bit network was down. But thanks for the heads up!

**Comment by nomatica** [comment]
Sorry for pulling you away for other things. I think it was a problem on my end.  Somehow my firewall was blocking the connection to your website.  As soon as I suspended the firewall to check, your site loaded.  Not sure if I flagged your blog accidentally in the past, or if the firewall software did it on its own.

**Comment by nomatica** [comment]
[ mcafee netguard blocks access... knowledgebase  ](https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&articleId=TS101116&_afrLoop=596461445566692&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25&centerWidth=100%25#!%40%40%3FshowFooter%3Dfalse%26_afrLoop%3D596461445566692%26articleId%3DTS101116%26leftWidth%3D0%2525%26showHeader%3Dfalse%26wc.contextURL%3D%252Fspaces%252Fcp%26rightWidth%3D0%2525%26centerWidth%3D100%2525%26_adf.ctrl-state%3D18ehjm5evb_174)

Just to follow up, it looks like the Mcafee might have flagged the ip address associated with your blog.  Not sure if is a shared hosted service or not.  While it has been a while since I was in this situation, I am assuming it is still a pain to try and address.    Mcafee knowledgebase provided this link:  https://www.trustedsource.org/en/feedback/url   Screenshots below. 

Image 1:
![flagged ip](https://user-images.githubusercontent.com/49659723/115739704-2354a280-a35c-11eb-8e11-e16d47014fe2.JPG)

Here is a screenshot when I enter the ip address into "trustedsource.org" 

![trustedsource](https://user-images.githubusercontent.com/49659723/115739727-28195680-a35c-11eb-921d-916d378df48c.JPG)

**Comment by karlicoss** [comment]
Hmm, thanks! Interesting that it doesn't flag it as high risk if I type in domain name :thinking:

**Comment by nomatica** [comment]
I also thought that strange. If your your domain is hosted on a shared server, its possible that someone/something on that server flagged mcafee's system. It is odd that the domain comes up clean, but the IP doesn't.  It looks like anyone can submit a change request on that page.  I wonder if someone who had the same experience as I, submitted the change request for your domain, but not the ip address?
